using Application.Common.Models;
using MediatR;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Application.DropDownData
{
    public class GetCountriesDropDownQuery : IRequest<IList<CountryDropDown>>
    {
        public GetCountriesDropDownQuery() { }
    }

    public class GetCountriesDropDownQueryHandler : IRequestHandler<GetCountriesDropDownQuery, IList<CountryDropDown>>
    {
        public async Task<IList<CountryDropDown>> Handle(GetCountriesDropDownQuery request, CancellationToken cancellationToken)
        {
            return await Task.Run(() =>
            {
                return CountryList.CountriesData.Select(c => new CountryDropDown
                {
                    Value = c.Key,
                    Label = c.Value[1], // Name
                    Description = c.Value[0] // 3 code
                }).ToList();
            });
        }
    }

    public class CountryDropDown : DropDownModel<string>
    {
    }

    public static class CountryList
    {
        public static Dictionary<string, string[]> CountriesData => new Dictionary<string, string[]>
        {
            { "CA", new string[] { "CAN", "Canada" } },
            { "AF", new string[] { "AFG" ,"Afghanistan"} },
            { "AX", new string[] { "ALA", "Aland Islands" } },
            { "AL", new string[] { "ALB", "Albania" } },
            { "DZ", new string[] { "DZA", "Algeria"} },
            { "AS", new string[] { "AAA", "American Samoa"} },
            { "AD", new string[] { "AAA", "Andorra"} },
            { "AO", new string[] { "AAA", "Angola"} },
            { "AI", new string[] { "AAA", "Anguilla"} },
            { "AA", new string[] { "AAA", "Antarctica"} },
            { "AG", new string[] { "AAA", "Antigua and Barbuda"} },
            { "AR", new string[] { "AAA", "Argentina"} },
            { "AM", new string[] { "AAA", "Armenia"} },
            { "AW", new string[] { "AAA", "Aruba"} },
            { "AU", new string[] { "AAA", "Australia"} },
            { "AT", new string[] { "AAA", "Austria"} },
            { "AZ", new string[] { "AAA", "Azerbaijan"} },
            { "BS", new string[] { "AAA", "Bahamas"} },
            { "BH", new string[] { "AAA", "Bahrain"} },
            { "BD", new string[] { "AAA", "Bangladesh"} },
            { "BB", new string[] { "AAA", "Barbados"} },
            { "BY", new string[] { "AAA", "Belarus"} },
            { "BE", new string[] { "AAA", "Belgium"} },
            { "BZ", new string[] { "AAA", "Belize"} },
            { "BJ", new string[] { "AAA", "Benin"} },
            { "BM", new string[] { "AAA", "Bermuda"} },
            { "BT", new string[] { "AAA", "Bhutan"} },
            { "BO", new string[] { "AAA", "Bolivia"} },
            { "BA", new string[] { "AAA", "Bosnia and Herzegowina"} },
            { "BW", new string[] { "AAA", "Botswana"} },
            { "BV", new string[] { "AAA", "Bouvet Island"} },
            { "BR", new string[] { "AAA", "Brazil"} },
            { "IO", new string[] { "AAA", "British Indian Ocean Territory"} },
            { "BN", new string[] { "AAA", "Brunei Darussalam"} },
            { "BG", new string[] { "AAA", "Bulgaria"} },
            { "BF", new string[] { "AAA", "Burkina Faso"} },
            { "BI", new string[] { "AAA", "Burundi"} },
            { "KH", new string[] { "AAA", "Cambodia"} },
            { "CM", new string[] { "AAA", "Cameroon"} },
            { "CV", new string[] { "AAA", "Cape Verde"} },
            { "KY", new string[] { "AAA", "Cayman Islands"} },
            { "CF", new string[] { "AAA", "Central African Republic"} },
            { "TD", new string[] { "AAA", "Chad"} },
            { "CL", new string[] { "AAA", "Chile"} },
            { "CN", new string[] { "AAA", "China"} },
            { "CX", new string[] { "AAA", "Christmas Island"} },
            { "CC", new string[] { "AAA", "Cocos (Keeling) Islands"} },
            { "CO", new string[] { "AAA", "Colombia"} },
            { "KM", new string[] { "AAA", "Comoros"} },
            { "CG", new string[] { "AAA", "Congo"} },
            { "CK", new string[] { "AAA", "Cook Islands"} },
            { "CR", new string[] { "AAA", "Costa Rica"} },
            { "CI", new string[] { "AAA", "Cote D'ivoire"} },
            { "HR", new string[] { "AAA", "Croatia (local name: Hrvatska)"} },
            { "CU", new string[] { "AAA", "Cuba"} },
            { "CY", new string[] { "AAA", "Cyprus"} },
            { "CZ", new string[] { "AAA", "Czech Republic"} },
            { "DK", new string[] { "AAA", "Denmark"} },
            { "DJ", new string[] { "AAA", "Djibouti"} },
            { "DM", new string[] { "AAA", "Dominica"} },
            { "DO", new string[] { "AAA", "Dominican Republic"} },
            { "TP", new string[] { "AAA", "East Timor"} },
            { "EC", new string[] { "AAA", "Ecuador"} },
            { "EG", new string[] { "AAA", "Egypt"} },
            { "SV", new string[] { "AAA", "El Salvador"} },
            { "GQ", new string[] { "AAA", "Equatorial Guinea"} },
            { "ER", new string[] { "AAA", "Eritrea"} },
            { "EE", new string[] { "AAA", "Estonia"} },
            { "ET", new string[] { "AAA", "Ethiopia"} },
            { "FK", new string[] { "AAA", "Falkland Islands (Malvinas)"} },
            { "FA", new string[] { "AAA", "Faroe Islands"} },
            { "FJ", new string[] { "AAA", "Fiji"} },
            { "FI", new string[] { "AAA", "Finland"} },
            { "FR", new string[] { "AAA", "France"} },
            { "FX", new string[] { "AAA", "France, Metropolitan"} },
            { "FG", new string[] { "AAA", "French Guiana"} },
            { "PF", new string[] { "AAA", "French Polynesia"} },
            { "FT", new string[] { "AAA", "French Southern Territories"} },
            { "GA", new string[] { "AAA", "Gabon"} },
            { "GM", new string[] { "AAA", "Gambia"} },
            { "GE", new string[] { "AAA", "Georgia"} },
            { "DE", new string[] { "AAA", "Germany"} },
            { "GH", new string[] { "AAA", "Ghana"} },
            { "GI", new string[] { "AAA", "Gibraltar"} },
            { "GR", new string[] { "AAA", "Greece"} },
            { "GL", new string[] { "AAA", "Greenland"} },
            { "GD", new string[] { "AAA", "Grenada"} },
            { "GP", new string[] { "AAA", "Guadeloupe"} },
            { "GU", new string[] { "AAA", "Guam"} },
            { "GG", new string[] { "AAA", "Guernsey"} },
            { "GT", new string[] { "AAA", "Guatemala"} },
            { "GN", new string[] { "AAA", "Guinea"} },
            { "GW", new string[] { "AAA", "Guinea Bissau"} },
            { "GY", new string[] { "AAA", "Guyana"} },
            { "HT", new string[] { "AAA", "Haiti"} },
            { "HM", new string[] { "AAA", "Heard and Mc Donald Islands"} },
            { "HN", new string[] { "AAA", "Honduras"} },
            { "HK", new string[] { "AAA", "Hong Kong"} },
            { "HU", new string[] { "AAA", "Hungary"} },
            { "IS", new string[] { "AAA", "Iceland"} },
            { "IN", new string[] { "AAA", "India"} },
            { "ID", new string[] { "AAA", "Indonesia"} },
            { "IR", new string[] { "AAA", "Iran (Islamic Republic Of)"} },
            { "IQ", new string[] { "AAA", "Iraq"} },
            { "IE", new string[] { "AAA", "Ireland"} },
            { "IM", new string[] { "AAA", "Isle of Man"} },
            { "IL", new string[] { "AAA", "Israel"} },
            { "IT", new string[] { "AAA", "Italy"} },
            { "JM", new string[] { "AAA", "Jamaica"} },
            { "JE", new string[] { "AAA", "Jersey"} },
            { "JP", new string[] { "AAA", "Japan"} },
            { "JO", new string[] { "AAA", "Jordan"} },
            { "KZ", new string[] { "AAA", "Kazakhstan"} },
            { "KE", new string[] { "AAA", "Kenya"} },
            { "KI", new string[] { "AAA", "Kiribati"} },
            { "KP", new string[] { "AAA", "Korea (North)"} },
            { "KR", new string[] { "AAA", "Korea (South)"} },
            { "KW", new string[] { "AAA", "Kuwait"} },
            { "KG", new string[] { "AAA", "Kyrgyzstan"} },
            { "LA", new string[] { "AAA", "Laos"} },
            { "LV", new string[] { "AAA", "Latvia"} },
            { "LB", new string[] { "AAA", "Lebanon"} },
            { "LS", new string[] { "AAA", "Lesotho"} },
            { "LR", new string[] { "AAA", "Liberia"} },
            { "LY", new string[] { "AAA", "Libya"} },
            { "LI", new string[] { "AAA", "Liechtenstein"} },
            { "LT", new string[] { "AAA", "Lithuania"} },
            { "LU", new string[] { "AAA", "Luxembourg"} },
            { "MO", new string[] { "AAA", "Macau"} },
            { "MK", new string[] { "AAA", "Macedonia, The Former Yugoslav Republic Of"} },
            { "MG", new string[] { "AAA", "Madagascar"} },
            { "MW", new string[] { "AAA", "Malawi"} },
            { "MY", new string[] { "AAA", "Malaysia"} },
            { "MV", new string[] { "AAA", "Maldives"} },
            { "ML", new string[] { "AAA", "Mali"} },
            { "MT", new string[] { "AAA", "Malta"} },
            { "MH", new string[] { "AAA", "Marshall Islands"} },
            { "MQ", new string[] { "AAA", "Martinique"} },
            { "MR", new string[] { "AAA", "Mauritania"} },
            { "MU", new string[] { "AAA", "Mauritius"} },
            { "YT", new string[] { "AAA", "Mayotte"} },
            { "MX", new string[] { "AAA", "Mexico"} },
            { "FS", new string[] { "AAA", "Micronesia, Federated States Of"} },
            { "MD", new string[] { "AAA", "Moldavia"} },
            { "MC", new string[] { "AAA", "Monaco"} },
            { "MN", new string[] { "AAA", "Mongolia"} },
            { "ME", new string[] { "AAA", "Montenegro"} },
            { "MS", new string[] { "AAA", "Montserrat"} },
            { "MA", new string[] { "AAA", "Morocco"} },
            { "MZ", new string[] { "AAA", "Mozambique"} },
            { "MM", new string[] { "AAA", "Myanmar"} },
            { "NA", new string[] { "AAA", "Namibia"} },
            { "NR", new string[] { "AAA", "Nauru"} },
            { "NP", new string[] { "AAA", "Nepal"} },
            { "NL", new string[] { "AAA", "Netherlands"} },
            { "AN", new string[] { "AAA", "Netherlands Antilles"} },
            { "NC", new string[] { "AAA", "New Caledonia"} },
            { "NZ", new string[] { "AAA", "New Zealand"} },
            { "NI", new string[] { "AAA", "Nicaragua"} },
            { "NE", new string[] { "AAA", "Niger"} },
            { "NG", new string[] { "AAA", "Nigeria"} },
            { "NU", new string[] { "AAA", "Niue"} },
            { "NF", new string[] { "AAA", "Norfolk Island"} },
            { "MP", new string[] { "AAA", "Northern Mariana Islands"} },
            { "NO", new string[] { "AAA", "Norway"} },
            { "OM", new string[] { "AAA", "Oman"} },
            { "PK", new string[] { "AAA", "Pakistan"} },
            { "PW", new string[] { "AAA", "Palau"} },
            { "PS", new string[] { "AAA", "Palestinian Territory"} },
            { "PA", new string[] { "AAA", "Panama"} },
            { "PG", new string[] { "AAA", "Papua New Guinea"} },
            { "PY", new string[] { "AAA", "Paraguay"} },
            { "PE", new string[] { "AAA", "Peru"} },
            { "PH", new string[] { "AAA", "Philippines"} },
            { "PN", new string[] { "AAA", "Pitcairn"} },
            { "PL", new string[] { "AAA", "Poland"} },
            { "PT", new string[] { "AAA", "Portugal"} },
            { "PR", new string[] { "AAA", "Puerto Rico"} },
            { "QA", new string[] { "AAA", "Qatar"} },
            { "RE", new string[] { "AAA", "Reunion"} },
            { "RO", new string[] { "AAA", "Romania"} },
            { "RU", new string[] { "AAA", "Russian Federation"} },
            { "RW", new string[] { "AAA", "Rwanda"} },
            { "BL", new string[] { "AAA", "Saint-Barthélemy"} },
            { "KN", new string[] { "AAA", "Saint Kitts and Nevis"} },
            { "LC", new string[] { "AAA", "Saint Lucia"} },
            { "MF", new string[] { "AAA", "Saint Martin"} },
            { "VC", new string[] { "AAA", "Saint Vincent and The Grenadines"} },
            { "WS", new string[] { "AAA", "Samoa"} },
            { "SM", new string[] { "AAA", "San Marino"} },
            { "ST", new string[] { "AAA", "Sao Tome and Principe"} },
            { "SA", new string[] { "AAA", "Saudi Arabia"} },
            { "SN", new string[] { "AAA", "Senegal"} },
            { "YU", new string[] { "AAA", "Serbia and Montenegro"} },
            { "SC", new string[] { "AAA", "Seychelles"} },
            { "SL", new string[] { "AAA", "Sierra Leone"} },
            { "SG", new string[] { "AAA", "Singapore"} },
            { "SK", new string[] { "AAA", "Slovakia (Slovak Republic)"} },
            { "SI", new string[] { "AAA", "Slovenia"} },
            { "SW", new string[] { "AAA", "Solomon Islands"} },
            { "SO", new string[] { "AAA", "Somalia"} },
            { "ZA", new string[] { "AAA", "South Africa"} },
            { "GS", new string[] { "AAA", "South Georgia and The South Sandwich Islands"} },
            { "SS", new string[] { "AAA", "South Sudan"} },
            { "ES", new string[] { "AAA", "Spain"} },
            { "LK", new string[] { "AAA", "Sri Lanka"} },
            { "SH", new string[] { "AAA", "St. Helena"} },
            { "PM", new string[] { "AAA", "St. Pierre and Miquelon"} },
            { "SD", new string[] { "AAA", "Sudan"} },
            { "SR", new string[] { "AAA", "Suriname"} },
            { "SJ", new string[] { "AAA", "Svalbard and Jan Mayen Islands"} },
            { "SZ", new string[] { "AAA", "Swaziland"} },
            { "SE", new string[] { "AAA", "Sweden"} },
            { "CH", new string[] { "AAA", "Switzerland"} },
            { "SY", new string[] { "AAA", "Syria"} },
            { "TW", new string[] { "AAA", "Taiwan, Province Of China"} },
            { "TJ", new string[] { "AAA", "Tajikistan"} },
            { "TZ", new string[] { "AAA", "Tanzania, United Republic Of"} },
            { "TH", new string[] { "AAA", "Thailand"} },
            { "TL", new string[] { "AAA", "Timor-Leste"} },
            { "TG", new string[] { "AAA", "Togo"} },
            { "TK", new string[] { "AAA", "Tokelau"} },
            { "TO", new string[] { "AAA", "Tonga"} },
            { "TT", new string[] { "AAA", "Trinidad and Tobago"} },
            { "TN", new string[] { "AAA", "Tunisia"} },
            { "TR", new string[] { "AAA", "Turkey"} },
            { "TM", new string[] { "AAA", "Turkmenistan"} },
            { "TC", new string[] { "AAA", "Turks and Caicos Islands"} },
            { "TV", new string[] { "AAA", "Tuvalu"} },
            { "UG", new string[] { "AAA", "Uganda"} },
            { "UA", new string[] { "AAA", "Ukraine"} },
            { "AE", new string[] { "AAA", "United Arab Emirates"} },
            { "UK", new string[] { "AAA", "United Kingdom"} },
            { "US", new string[] { "AAA", "United States"} },
            { "UM", new string[] { "AAA", "United States Minor Outlying Islands"} },
            { "UY", new string[] { "AAA", "Uruguay"} },
            { "UZ", new string[] { "AAA", "Uzbekistan"} },
            { "VU", new string[] { "AAA", "Vanuatu"} },
            { "VA", new string[] { "AAA", "Vatican City State (Holy See)"} },
            { "VE", new string[] { "AAA", "Venezuela"} },
            { "VN", new string[] { "AAA", "Vietnam"} },
            { "VG", new string[] { "AAA", "Virgin Islands (British)"} },
            { "VI", new string[] { "AAA", "Virgin Islands (U.S.)"} },
            { "WF", new string[] { "AAA", "Wallis and Futuna Islands"} },
            { "WH", new string[] { "AAA", "Western Sahara"} },
            { "YE", new string[] { "AAA", "Yemen"} },
            { "ZR", new string[] { "AAA", "Zaire"} },
            { "ZM", new string[] { "AAA", "Zambia"} },
            { "ZW", new string[] { "AAA", "Zimbabwe"} }
        };
    }
}
