namespace Domain.Entities
{
    public class PandaDocTemplate : BaseEntity<int>
    {
        /**
        * ID of PandaDoc Template.
        * This ID is generated by PandaDoc when a new template is created. 
        * This should be unique and immutable after creation
        */
        public string TemplateId { get; set; }
        /**
        * Name of PandaDoc Template.
        * This Name is generated by PandaDoc when a new template is created.
        */
        public string Name { get; set; }
        /**
         * Type of PandaDoc Template
         * value should be able to be parsed to enum 'PandaDocTemplateType'
         */
        public string Type { get; set; }
        /**
       * ID of the school which this template is uploaded by.
       * The SchoolID is a foreign key referencing school table
       */
        public int SchoolId { get; set; }
        public School School { get; set; }
    }
}